name: Build
on: [push]
jobs:
  build:
    name: Build docker image for Linkfix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: franzdiebold/github-env-vars-action@v1.0.0
      - name: Build the Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: matousdz/linkfix
          tag_with_ref: true
          tag_with_sha: true
          build_args: BUILD_REV=unknown,COMMIT_DATE=unknown
